---
title: "Github with RStudio"
author: "Written by the NKU Data Science Club"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is Git/Github?

From the git website itself:

"Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency."

Put simply, git is a great way to manage your code over time, especially one projects where you're working with multiple people. If you've ever been in a group coding project, you've probably emailed versions of datasets and code back and forth trying to make progress, ending up with a program whose name is something like "FINAL ANALYSIS V4.5 ACTUALLY FINAL THIS TIME FOR REAL". Git helps you manage this for the programs you have on your machine, and github makes those files available anywhere, for anyone you want, at anytime. You're most likely reading this tutorial on Github right now, so you can also see the power it has to host markdown documents that are legible and easy to find. 

To begin, let's get git setup, see what it can do, and then get started with GitHub. 

## Git Installation and Setup

### The Github Desktop Way

### The Command Line Way

#### Windows

If you're on windows, just go to https://git-scm.com/download/win, and the download hould happen automatically. Just click the executable and follow the steps provided!

#### Mac

I haven't tried this, since I don't have mac, but apparentrly you can type `git` on the terminal, and it will prompt you to install git!

## Github Setup

## Creating a Repository

## Commits, Pushes, and Pulls

## Github and RStudio

## Working on the NKU-DSC Repository